# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-21 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='itle',
            new_name='title',
        ),
    ]
